import sys
from PyQt5 import uic
from PyQt5 import QtCore
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import pyqtgraph as pg
import numpy as np



class QssEditorWidget(QWidget):
    qssEditorSignal = QtCore.pyqtSignal(int)

    def __init__(self, inputModel):
        super(QssEditorWidget, self).__init__()
        self.ui = uic.loadUi("QtDesigner/QssEditorWidget.ui", self)
        self.ui.qssEditorCheckBox.stateChanged.connect(self.handleQssEditorCheckBox)
        self.model = inputModel
        sshFile = "Styles/Style.qss"
        with open(sshFile, 'r') as fh:
            self.ui.qssEdit.setText(fh.read())

        self.ui.qssFrame.setStyleSheet(self.ui.qssEdit.toPlainText())

        self.ui.applyButton.clicked.connect(self.applyQss)

        self.ui.elementComboBox.addItems([
                "QAbstractScrollArea",
                "QCheckBox",
                "QCheckBox::indicator",
                "QColumnView",
                "QColumnView::left-arrow",
                "QColumnView::right-arrow",
                "QComboBox",
                "QComboBox::drop-down",
                "QComboBox::down-arrow",
                "QDateEdit",
                "QDateTimeEdit",
                "QDialog",
                "QDialogButtonBox",
                "QDockWidget",
                "QDockWidget::title",
                "QDoubleSpinBox",
                "QFrame",
                "QGroupBox",
                "QGroupBox::title",
                "QGroupBox::indicator",
                "QHeaderView",
                "QLabel",
                "QLineEdit",
                "QListView",
                "QListView::item",
                "QListWidget",
                "QMainWindow",
                "QMainWindow::separator",
                "QMenu",
                "QMenu::item",
                "QMenu::indicator",
                "QMenu::separator",
                "QMenuBar",
                "QMenuBar::item",
                "QMessageBox",
                "QProgressBar",
                "QProgressBar::chunk",
                "QProgressBar::chunk",
                "QPushButton",
                "QPushButton::menu-indicator",
                "QRadioButton",
                "QRadioButton::indicator",
                "QScrollBar",
                "QScrollBar::handle",
                "QScrollBar::add-line",
                "QScrollBar::sub-line",
                "QScrollBar::add-page",
                "QScrollBar::sub-page",
                "QSizeGrip",
                "QSlider",
                "QSlider::handle",
                "QSpinBox",
                "QSpinBox::up-button",
                "QSpinBox::up-arrow",
                "QSpinBox::down-button",
                "QSpinBox::down-arrow",
                "QSplitter",
                "QSplitter::handle",
                "QStatusBar",
                "QStatusBar::item",
                "QTabBar",
                "QTabBar::tab",
                "QTabBar::close-button",
                "QTabBar::tear",
                "QTabWidget",
                "QTabWidget::pane",
                "QTabWidget::left-corner",
                "QTabWidget::right-corner",
                "QTabWidget::tab-bar",
                "QTableView",
                "QTableWidget",
                "QTextEdit",
                "QTimeEdit",
                "QToolBar",
                "QToolBar::separator",
                "QToolBar::handle",
                "QToolButton",
                "QToolButton::menu-indicator",
                "QToolButton::menu-button",
                "QToolButton::up-arrow",
                "QToolButton::down-arrow",
                "QToolButton::left-arrow",
                "QToolButton::right-arrow",
                "QToolBox",
                "QToolBox::tab",
                "QToolTip",
                "QTreeView",
                "QTreeView::branch",
                "QTreeView::item",
                "QTreeWidget",
                "QWidget"
                ])

        self.ui.propertyComboBox.addItems([
                "alternate-background-color",
                "background",
                "background-color",
                "background-image",
                "background-repeat",
                "background-position",
                "background-attachment",
                "background-clip",
                "background-origin",
                "border",
                "border-top",
                "border-right",
                "border-bottom",
                "border-left",
                "border-color",
                "border-top-color",
                "border-right-color",
                "border-bottom_color",
                "border-left-color",
                "border-image",
                "border-radius",
                "border-top-left-radius",
                "border-top-right-radius",
                "border-bottom-right-radius",
                "border-bottom-left-radius",
                "border-style",
                "border-top-style",
                "border-right-style",
                "border-bottom-style",
                "border-left-style",
                "border-width",
                "border-top-width",
                "border-right-width",
                "border-bottom-width",
                "border-left-width",
                "bottom",
                "button-layout",
                "color",
                "dialogbuttonbox-buttons-have-icons",
                "font",
                "font-family",
                "font-size",
                "font-style",
                "font-weight",
                "gridline-color",
                "height",
                "icon-size",
                "image",
                "image-position",
                "left",
                "lineedit-password-character",
                "lineedit-password-mask-delay",
                "margin",
                "margin-top",
                "margin-right",
                "margin-bottom",
                "margin-left",
                "max-height",
                "max-width",
                "messagebox-text-interaction-flags",
                "min-height",
                "min-width",
                "opacity",
                "outline",
                "outline-color",
                "outline-offset",
                "outline-style",
                "outline-radius",
                "outline-bottom-left-radius",
                "outline-bottom-right-radius",
                "outline-top-left-radius",
                "outline-top-right-radius",
                "padding",
                "padding-top",
                "padding-right",
                "padding-bottom",
                "padding-left",
                "paint-alternating-row-colors-for-empty-area",
                "position",
                "right",
                "selection-background-color",
                "selection-color",
                "show-decoration-selected",
                "spacing",
                "subcontrol-origin",
                "subcontrol-position",
                "text-align",
                "text-decoration",
                "top",
                "width"
                ])

        self.ui.show()

    def applyQss(self):
        self.ui.qssFrame.setStyleSheet(self.ui.qssEdit.toPlainText())

    def handleQssEditorCheckBox(self, state):
        self.qssEditorSignal.emit(state)
